services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - APPNAME=app
    volumes:
      - shared_data:/shared
    depends_on:
      - db
      - mlflow
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kewdetect
      - POSTGRES_HOST_AUTH_METHOD=trust
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.4.0
    expose:
      - 5000
    volumes:
      - shared_data:/shared
    
volumes:
  postgres_data:
  shared_data:
  